KAFKA-12617 Convert MetadataRequestTest to use ClusterTest (#21101)
# Description
Changed `MetadataRequestTest` to use `ClusterTest`

# Changes
Added `ClusterInstance#createTopicWithAssignment` to align with
`KafkaServerTestHarness#createTopicWithAssignment`

Helper functions inherited from base classes were rewritten in
`AbstractMetadataRequestTest`

# Issue
`testIsrAfterBrokerShutDownAndJoinsBack` fails because of thread leak:
```
org.opentest4j.AssertionFailedError: Thread leak detected: JMX server
connection timeout 28 ==>
Expected :true
Actual   :false
```

`testAliveBrokersWithNoTopics` would also fail if the last
`checkMetadata` is removed.

Reviewers: Chia-Ping Tsai <chia7712@gmail.com>