MINOR: Delegate version updates to Gradle in release script (#22031)
Remove `SNAPSHOT` in `version.py`, so
`StreamsUpgradeTest.test_app_upgrade` doesn't have following error.

```
    TimeoutError("Did expect to read 'Kafka version.*4.2.1.*SNAPSHOT'
from ducker@ducker06")
Traceback (most recent call last):
  File
"/usr/local/lib/python3.10/dist-packages/ducktape/tests/runner_client.py",
line 351, in _do_run
    data = self.run_test()
  File
"/usr/local/lib/python3.10/dist-packages/ducktape/tests/runner_client.py",
line 411, in run_test
    return self.test_context.function(self.test)
  File "/usr/local/lib/python3.10/dist-packages/ducktape/mark/_mark.py",
line 438, in wrapper
    return functools.partial(f, *args, **kwargs)(*w_args, **w_kwargs)
  File
"/opt/kafka-dev/tests/kafkatest/tests/streams/streams_application_upgrade_test.py",
line 114, in test_app_upgrade
    self.restart_all_nodes_with(from_version, to_version)
  File
"/opt/kafka-dev/tests/kafkatest/tests/streams/streams_application_upgrade_test.py",
line 190, in restart_all_nodes_with
    self.wait_for_verification(self.processor1, kafka_version_str,
self.processor1.LOG_FILE)
  File
"/opt/kafka-dev/tests/kafkatest/tests/streams/streams_application_upgrade_test.py",
line 214, in wait_for_verification
    wait_until(lambda: self.verify_from_file(processor, message, file)
>= num_lines,
  File "/usr/local/lib/python3.10/dist-packages/ducktape/utils/util.py",
line 58, in wait_until
    raise TimeoutError(err_msg() if callable(err_msg) else err_msg) from
last_exception
ducktape.errors.TimeoutError: Did expect to read 'Kafka
version.*4.2.1.*SNAPSHOT' from ducker@ducker06
```

Reviewers: Chia-Ping Tsai <chia7712@gmail.com>