MINOR: Fix default server config in BenchmarkConfigUtils (#21839)
Since

https://github.com/apache/kafka/commit/ed367cf22427277e84cf54a806f411c0561b3f09
when running benchmarks that call `createDummyBrokerConfig()` we get the
following error:
```
java.lang.IllegalArgumentException: requirement failed: If process.roles
contains just the 'broker' role, the node id 0 must not be included in
the set of voters controller.quorum.voters=Set(0)
```

Reviewers: Chia-Ping Tsai <chia7712@gmail.com>