KAFKA-20524: Improve reset offset usability (#22607)
This is part of the implementation of

https://cwiki.apache.org/confluence/display/KAFKA/KIP-1323%3A+Initialization+of+share+group+offsets+from+a+specific+offset+or+a+file.

Improves the readability of the usage messages for the command-line
tools for consumer groups, share groups and streams groups. For example,
the `--export` option used to say `"Export offset information in CSV
format"` or `"Export operation execution to a CSV file"` which are a bit
misleading. The new text is `"Generate offset reset information in CSV
format for export to a file"`.

Also improves the output when `bin/kafka-share-groups.sh` is used to
reset the offsets for a group which is not a share group.

Before:
```
% bin/kafka-share-groups.sh --bootstrap-server localhost:9092
--reset-offsets --group CG1 --to-current --topic T1 --execute

Error: Executing share group command failed due to Failed altering group
offsets for the following partitions: [T1-0]
org.apache.kafka.common.errors.GroupIdNotFoundException: Failed altering
group offsets for the following partitions: [T1-0]
```

After:
```
% bin/kafka-share-groups.sh --bootstrap-server localhost:9092
--reset-offsets --group CG1 --to-current --topic T1 --execute

Error: Executing share group command failed due to Group CG1 is not a
share group. Failed altering group offsets for the following partitions:
[T1-0]
org.apache.kafka.common.errors.GroupIdNotFoundException: Group CG1 is
not a share group. Failed altering group offsets for the following
partitions: [T1-0]
```

The difference is that the error message `"Group CG1 is not a share
group"` from the broker is included in the output.

Reviewers: Prakash Tanaji <prakashtanaji@hotmail.com>, nileshkumar3
 <nileshkumar3@gmail.com>, Lianet Magrans <lmagrans@confluent.io>