MINOR: Use SHA256withRSA instead of SHA1withRSA when running SslTransportLayerTest (#20961)
`SHA1withRSA` is disabled in some linux distribution, such as Fedora 43
server, which results in the following error. Hence, this PR adopts the
solution suggested by @gaurav-narula in
https://github.com/apache/kafka/pull/20561#issuecomment-3378701638,
which is to use `SHA256withRSA` instead of `SHA1withRSA`

```
Gradle Test Run :clients:test > Gradle Test Executor 28 > Tls13SslFactoryTest > testSslFactoryConfiguration() FAILED
    org.apache.kafka.common.config.ConfigException: Invalid value javax.net.ssl.SSLHandshakeException: (handshake_failure) No available authentication scheme for configuration A client SSLEngine created with the provided settings can't connect to a server SSLEngine created with those settings.
        at app//org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:105)
        at app//org.apache.kafka.common.security.ssl.SslFactoryTest.testSslFactoryConfiguration(SslFactoryTest.java:80)
        at java.base@21.0.9/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base@21.0.9/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base@21.0.9/java.util.ArrayList.forEach(ArrayList.java:1596)
```

Reviewers: Chia-Ping Tsai <chia7712@gmail.com>
(cherry picked from commit d251ec045f200c8fa48d44a1b27408b320161f8b)