MINOR: Skip testDsaKeyPair when DSA algorithm is not supported (#20985)
Create this PR to merge to 3.9 with #20967 due to the cherry pick fail
https://github.com/apache/kafka/pull/20967#issuecomment-3573385487


Fix:
```
javax.net.ssl|ERROR|E1|echoserver|2025-11-24 14:34:37.602 CST|TransportContext.java:375|Fatal (HANDSHAKE_FAILURE): no cipher suites in common (
"throwable" : {
  javax.net.ssl.SSLHandshakeException: (handshake_failure) no cipher suites in common
  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:130)
  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:370)
  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:317)
  	at java.base/sun.security.ssl.ServerHello$T12ServerHelloProducer.chooseCipherSuite(ServerHello.java:459)
  	at java.base/sun.security.ssl.ServerHello$T12ServerHelloProducer.produce(ServerHello.java:285)
  	at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:437)
  	at java.base/sun.security.ssl.ClientHello$T12ClientHelloConsumer.consume(ClientHello.java:1110)
  	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:843)
  	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:798)
  	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:393)
  	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:477)
  	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1273)
  	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1260)
  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
  	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1205)
  	at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:444)
  	at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:533)
  	at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:382)
  	at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:302)
  	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
  	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:548)
  	at org.apache.kafka.common.network.Selector.poll(Selector.java:486)
  	at org.apache.kafka.common.network.NioEchoServer.run(NioEchoServer.java:221)}
```

Reviewers: PoAn Yang <payang@apache.org>, Chia-Ping Tsai
<chia7712@gmail.com>