MINOR: Fix broken KRaftMetadataRequestBenchmark test due to uninitialised ShareCoordinator (#21214)
Currently the `KRaftMetadataRequestBenchmark` is failing with the
following error:
```
java.lang.RuntimeException: You must set shareCoordinator
        at
kafka.server.builders.KafkaApisBuilder.build(KafkaApisBuilder.java:197)
        at
org.apache.kafka.jmh.metadata.KRaftMetadataRequestBenchmark.createKafkaApis(KRaftMetadataRequestBenchmark.java:210)
        at
org.apache.kafka.jmh.metadata.KRaftMetadataRequestBenchmark.setup(KRaftMetadataRequestBenchmark.java:134)
        at
org.apache.kafka.jmh.metadata.jmh_generated.KRaftMetadataRequestBenchmark_testRequestToJson_jmhTest._jmh_tryInit_f_kraftmetadatarequestbenchmark0_G(KRaftMetadataRequestBenchmark_testRequestToJson_jmhTest.java:451)
        at
org.apache.kafka.jmh.metadata.jmh_generated.KRaftMetadataRequestBenchmark_testRequestToJson_jmhTest.testRequestToJson_AverageTime(KRaftMetadataRequestBenchmark_testRequestToJson_jmhTest.java:164)
        at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
        at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at
org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:527)
        at
org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:504)
        at
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

After the fix, here are the results:

```
./jmh-benchmarks/jmh.sh -f 1 -i 2 -wi 2
org.apache.kafka.jmh.metadata.KRaftMetadataRequestBenchmark

Benchmark
(partitionCount)  (topicCount)  Mode  Cnt         Score   Error  Units
KRaftMetadataRequestBenchmark.testMetadataRequestForAllTopics
10           500  avgt    2    802296.940          ns/op
KRaftMetadataRequestBenchmark.testMetadataRequestForAllTopics
10          1000  avgt    2   1554324.508          ns/op
KRaftMetadataRequestBenchmark.testMetadataRequestForAllTopics
10          5000  avgt    2  20675689.357          ns/op
KRaftMetadataRequestBenchmark.testMetadataRequestForAllTopics
20           500  avgt    2   1202763.607          ns/op
KRaftMetadataRequestBenchmark.testMetadataRequestForAllTopics
20          1000  avgt    2   2759721.061          ns/op
KRaftMetadataRequestBenchmark.testMetadataRequestForAllTopics
20          5000  avgt    2  26355078.691          ns/op
KRaftMetadataRequestBenchmark.testMetadataRequestForAllTopics
50           500  avgt    2   3186329.977          ns/op
KRaftMetadataRequestBenchmark.testMetadataRequestForAllTopics
50          1000  avgt    2   6383024.540          ns/op
KRaftMetadataRequestBenchmark.testMetadataRequestForAllTopics
50          5000  avgt    2  49264850.641          ns/op
KRaftMetadataRequestBenchmark.testRequestToJson
10           500  avgt    2       375.849          ns/op
KRaftMetadataRequestBenchmark.testRequestToJson
10          1000  avgt    2       402.769          ns/op
KRaftMetadataRequestBenchmark.testRequestToJson
10          5000  avgt    2       380.075          ns/op
KRaftMetadataRequestBenchmark.testRequestToJson
20           500  avgt    2       377.686          ns/op
KRaftMetadataRequestBenchmark.testRequestToJson
20          1000  avgt    2       380.253          ns/op
KRaftMetadataRequestBenchmark.testRequestToJson
20          5000  avgt    2       389.466          ns/op
KRaftMetadataRequestBenchmark.testRequestToJson
50           500  avgt    2       385.464          ns/op
KRaftMetadataRequestBenchmark.testRequestToJson
50          1000  avgt    2       390.164          ns/op
KRaftMetadataRequestBenchmark.testRequestToJson
50          5000  avgt    2       408.207          ns/op
```

Reviewers: Andrew Schofield <aschofield@confluent.io>